// Meals list (converted manually from CSV)

const meals = [
  {
    "recipe": "White bean quesadilla",
    "genre": "mexican",
    "primaryStarch": "tortilla",
    "rating": 3,
    "source": "modern way to cook",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Breakfast for dinner",
    "genre": "other",
    "primaryStarch": "potato",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Vegetarian skillet chili",
    "genre": "mexican",
    "primaryStarch": "",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Scratchy husband pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Spicy peanut noodles",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "Ali Slaigle",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Salmon broccoli with ginger",
    "genre": "other",
    "primaryStarch": "",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Pomelo noodles",
    "genre": "other",
    "primaryStarch": "pasta",
    "rating": 2,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Lauki sabzi",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 3,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Vegan mac & cheese",
    "genre": "other",
    "primaryStarch": "pasta",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Lauren Toyota's Vegan Cookbook",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Spinach and feta saag paneer",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 5,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 2,
    "notes": ""
  },
  {
    "recipe": "Red pepper potato & peanut sabzi",
    "genre": "indian",
    "primaryStarch": "potato",
    "rating": 3,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Turmeric and coconut aloo gobi",
    "genre": "indian",
    "primaryStarch": "potato",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Golden miso potato salad",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Egg salad",
    "genre": "other",
    "primaryStarch": "bread",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Carrot poutine",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "Trois Fois par Jour",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Chana masala",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Matar paneer",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Chile peanut rice",
    "genre": "indian",
    "primaryStarch": "rice",
    "rating": 3,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Caramelized ginger mushrooms",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Veggie stir fry",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Veggie stir fry with peanut sauce",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Sweet potatoes, cauliflour, and feta",
    "genre": "other",
    "primaryStarch": "sweet potato",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Pasta with tomatoes, capers, and olives",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Instant pot Thai curry",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 4,
    "source": "other",
    "sourceDetails": "Graham",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Gochujang fried rice",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Cheesy cauliflour toasts",
    "genre": "other",
    "primaryStarch": "bread",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Jollof rice",
    "genre": "other",
    "primaryStarch": "rice",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Tacos with quick pickled onions",
    "genre": "mexican",
    "primaryStarch": "tortilla",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 2,
    "notes": ""
  },
  {
    "recipe": "Aloo gobi",
    "genre": "indian",
    "primaryStarch": "potato",
    "rating": 5,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Ricotta and lemon pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 3,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Indianish nachos",
    "genre": "indian",
    "primaryStarch": "tortilla",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Instant pot chana dal",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Website",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Tofu makhani",
    "genre": "indian",
    "primaryStarch": "naan",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Shrimp pad thai",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Veggie pad thai",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 3,
    "source": "other",
    "sourceDetails": "Minimalist Baker",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Ramen with veggies",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Ramen with cheese and egg",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Double lime, asparagus, cashew, and ginger stir fry",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Lemon and cardamom upside-down cake",
    "genre": "other",
    "primaryStarch": "",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Creamy miso pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Polenta with tomato sauce",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Sweet potato & green chili masala dosa",
    "genre": "indian",
    "primaryStarch": "tortilla",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 124,
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Leek, feta, and lemon polenta cake",
    "genre": "other",
    "primaryStarch": "",
    "rating": 2,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Avocado and popped bean burritos",
    "genre": "mexican",
    "primaryStarch": "tortilla",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Sweet potato enchiladas",
    "genre": "mexican",
    "primaryStarch": "tortilla",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Mushroom bacon burgers",
    "genre": "other",
    "primaryStarch": "bread",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Lauren Toyota's Vegan Comfort Food",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Almond satay bowl with tempeh",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Vegan jackfruit pulled pork",
    "genre": "mexican",
    "primaryStarch": "bread",
    "rating": 4,
    "source": "other",
    "sourceDetails": "Website",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Buffalo cauliflour wings",
    "genre": "asian",
    "primaryStarch": "bread",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Lauren Toyota",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Cacio e pepe with cashew cheese",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Mustard seed & curry carrots",
    "genre": "side",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Pav bhaji",
    "genre": "indian",
    "primaryStarch": "potato",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Cheesy chili broccoli",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Gnocchi with gorgonzola cheese sauce",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Gnocchi with tomato sauce",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Leek quiche",
    "genre": "other",
    "primaryStarch": "pie crust",
    "rating": 4,
    "source": "other",
    "sourceDetails": "The Kitchn",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Priya's dal",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Malaysian ramen",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 2,
    "notes": ""
  },
  {
    "recipe": "Broccoli cheddar soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "Copycat Panera recipe",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Salmon, potatoes, and snap peas",
    "genre": "other",
    "primaryStarch": "potato",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Kua Kling curry with mushrooms and tempeh",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Creamy turmeric pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Indianish baked beans",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Quinoa miso bowl",
    "genre": "asian",
    "primaryStarch": "quinoa",
    "rating": 5,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Noodle bowl with orange, maple, miso dressing",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 5,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Salmon, miso rice, and ginger scallions",
    "genre": "asian",
    "primaryStarch": "rice",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Baingan bharta",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 2,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Red lentil and chickpea curry",
    "genre": "indian",
    "primaryStarch": "rice",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Omelettes",
    "genre": "other",
    "primaryStarch": "",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Chickpea and tomato chhole stew",
    "genre": "indian",
    "primaryStarch": "naan",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 153,
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Naan pizzas",
    "genre": "other",
    "primaryStarch": "naan",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Perogies",
    "genre": "other",
    "primaryStarch": "potato",
    "rating": 3,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "African groundnut peanut soup stew",
    "genre": "other",
    "primaryStarch": "",
    "rating": 3,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Indian spiced lentil cauliflower soup",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Tex-mex Mexican rice casserole",
    "genre": "other",
    "primaryStarch": "rice",
    "rating": 5,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Broccoli and cashew cheese burritos",
    "genre": "other",
    "primaryStarch": "quinoa",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Tomato-basil pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "One-pot lemon, pea, and asparagus pasta",
    "genre": "italian",
    "primaryStarch": "pasta",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "New potato, tortilla, and halloumi",
    "genre": "other",
    "primaryStarch": "potato",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Cucumber salad with sichuan pepper",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Spicy sichuan noodes",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "Florence Fabricant",
    "url": "",
    "pageNumber": "",
    "multiplier": 1,
    "notes": ""
  },
  {
    "recipe": "Halloumi and new potato tortilla",
    "genre": "mediterranean",
    "primaryStarch": "potato",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Summer taco salad",
    "genre": "mexican",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 251,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Thai-Chinese-style spicy peanut noodles",
    "genre": "asian",
    "primaryStarch": "noodles",
    "rating": 4,
    "source": "other",
    "sourceDetails": "thai cookbook (Heather's iPhone)",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Anna Jones pizza dough",
    "genre": "other",
    "primaryStarch": "",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Roast avocado tacos",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 281,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Roti stirfry with sweet potatoes, cauliflower, and broccoli",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Harissa and lime halloumi",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 272,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Dhal-baked eggs",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 314,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Roast cauliflower cheddar soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 319,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Sri Lankan squash dhal",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 332,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Poached egg and mushrooms on brioche",
    "genre": "other",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Gordon Ramsay masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Saag paneer spanikopita",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Paranthas",
    "genre": "side",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Beetroot borani and harissa yogurt",
    "genre": "side",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 234,
    "multiplier": "",
    "notes": "Yogurt on pg. 273, flatbread on page 456"
  },
  {
    "recipe": "Salmon and roasted beet salad",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "oh she glows 1",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 113,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Beet and avocado kachumber",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Munammara and hummus",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Grilled caesar salad with crispy chickpeas",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 248,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Kaddu sweet-and-sour butternut squash",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 4,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 115,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Smoky Thai massaman curry with shrimp",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 409,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Tray bake with feta",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 352,
    "multiplier": "",
    "notes": "Can swap out veggies"
  },
  {
    "recipe": "Figs, ricotta, radicchio and almonds",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 3,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 364,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Raclette",
    "genre": "other",
    "primaryStarch": "potato",
    "rating": 5,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Moroccan lentil soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "from Kim by email",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Santa fe soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "from Kim by email",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Party bao buns",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 4,
    "source": "modern cook's year",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 410,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Artichoke dip",
    "genre": "side",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "from Vicki by email",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Almond sauce stir fry",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 4,
    "source": "oh she glows 2",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Eggs benedict with mushroom bacon",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": "Mushroom bacon from the vegan mac and cheese recipe"
  },
  {
    "recipe": "Dinner rolls",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "America's Test Kitchen",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Shakshuka",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "nyt cooking",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": 2,
    "notes": ""
  },
  {
    "recipe": "Gochujang shrimp",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 4,
    "source": "nyt cooking",
    "sourceDetails": "Ali Slaigle",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Split pea soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 5,
    "source": "rebar",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 119,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Butternut squash soup",
    "genre": "other",
    "primaryStarch": "",
    "rating": 2,
    "source": "rebar",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 134,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Buttery beets and grapefruit",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 92,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Stir fry celery with peanuts",
    "genre": "asian",
    "primaryStarch": "",
    "rating": 4,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 104,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Pan-roasted Romanesco with toasted nuts and crispy bits",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 4,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 90,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Charred broccoli salad with dates",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 106,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Spaghetti with artichokes",
    "genre": "italian",
    "primaryStarch": "",
    "rating": 4,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 137,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Smokey feta and peas",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Smacked cucumber salad with sumac pickled onions",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Roasted cauliflower and harissa",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Salmon and prawns in tomato sauce with tahini",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Pasta with butternut squash and yogurt sauce",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Shatta",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Herb shakshuka",
    "genre": "mediterranean",
    "primaryStarch": "",
    "rating": 3,
    "source": "other",
    "sourceDetails": "Ottolenghi masterclass",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Fox-style chickpeas",
    "genre": "other",
    "primaryStarch": "",
    "rating": 4,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 232,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Salmon with cauliflower tartare",
    "genre": "other",
    "primaryStarch": "",
    "rating": 5,
    "source": "where cooking begins",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 186,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Caramelized onion dhal",
    "genre": "indian",
    "primaryStarch": "",
    "rating": 5,
    "source": "indianish",
    "sourceDetails": "",
    "url": "",
    "pageNumber": 160,
    "multiplier": "",
    "notes": ""
  },
  {
    "recipe": "Saganaki",
    "genre": "side",
    "primaryStarch": "",
    "rating": 5,
    "source": "other",
    "sourceDetails": "",
    "url": "",
    "pageNumber": "",
    "multiplier": "",
    "notes": ""
  }
];

export default meals;
